export interface StandardMedication {
  brandName: string;
  genericName: string;
  form: string;
  strength: string;
  defaultDosage: string;
  defaultFrequency: string;
  defaultDuration: string;
  unitPrice: number;
  stockQuantity: number;
  minStockLevel: number;
}

export const FORMULARY_MEDICATIONS: StandardMedication[] = [
  {
    brandName: "Amoxil",
    genericName: "Amoxicillin",
    form: "Capsule",
    strength: "500mg",
    defaultDosage: "500mg",
    defaultFrequency: "1-0-1 (Twice daily after meals)",
    defaultDuration: "5 days",
    unitPrice: 0.85,
    stockQuantity: 450,
    minStockLevel: 50,
  },
  {
    brandName: "Augmentin",
    genericName: "Amoxicillin / Clavulanate",
    form: "Tablet",
    strength: "625mg",
    defaultDosage: "625mg",
    defaultFrequency: "1-0-1 (Twice daily)",
    defaultDuration: "7 days",
    unitPrice: 1.75,
    stockQuantity: 280,
    minStockLevel: 40,
  },
  {
    brandName: "Panadol / Tylenol",
    genericName: "Paracetamol (Acetaminophen)",
    form: "Tablet",
    strength: "500mg",
    defaultDosage: "500mg - 1000mg",
    defaultFrequency: "PRN (Every 6 hours as needed for fever/pain)",
    defaultDuration: "3 days",
    unitPrice: 0.25,
    stockQuantity: 1200,
    minStockLevel: 100,
  },
  {
    brandName: "Brufen",
    genericName: "Ibuprofen",
    form: "Tablet",
    strength: "400mg",
    defaultDosage: "400mg",
    defaultFrequency: "1-0-1 (Twice daily with meals)",
    defaultDuration: "5 days",
    unitPrice: 0.40,
    stockQuantity: 650,
    minStockLevel: 60,
  },
  {
    brandName: "Glucophage",
    genericName: "Metformin Hydrochloride",
    form: "Tablet",
    strength: "500mg",
    defaultDosage: "500mg",
    defaultFrequency: "1-0-1 (Twice daily with dinner)",
    defaultDuration: "30 days",
    unitPrice: 0.50,
    stockQuantity: 800,
    minStockLevel: 100,
  },
  {
    brandName: "Norvasc",
    genericName: "Amlodipine",
    form: "Tablet",
    strength: "5mg",
    defaultDosage: "5mg",
    defaultFrequency: "1-0-0 (Once daily in the morning)",
    defaultDuration: "30 days",
    unitPrice: 0.65,
    stockQuantity: 520,
    minStockLevel: 80,
  },
  {
    brandName: "Lipitor",
    genericName: "Atorvastatin",
    form: "Tablet",
    strength: "20mg",
    defaultDosage: "20mg",
    defaultFrequency: "0-0-1 (Once daily at bedtime)",
    defaultDuration: "30 days",
    unitPrice: 1.10,
    stockQuantity: 410,
    minStockLevel: 50,
  },
  {
    brandName: "Losec / Prilosec",
    genericName: "Omeprazole",
    form: "Capsule",
    strength: "20mg",
    defaultDosage: "20mg",
    defaultFrequency: "1-0-0 (Once daily before breakfast)",
    defaultDuration: "14 days",
    unitPrice: 0.90,
    stockQuantity: 360,
    minStockLevel: 45,
  },
  {
    brandName: "Zyrtec",
    genericName: "Cetirizine Hydrochloride",
    form: "Tablet",
    strength: "10mg",
    defaultDosage: "10mg",
    defaultFrequency: "0-0-1 (Once daily at night)",
    defaultDuration: "10 days",
    unitPrice: 0.45,
    stockQuantity: 500,
    minStockLevel: 60,
  },
  {
    brandName: "Ventolin",
    genericName: "Salbutamol (Albuterol)",
    form: "Inhaler",
    strength: "100mcg/dose",
    defaultDosage: "2 puffs",
    defaultFrequency: "PRN (Every 4-6 hours as needed for wheeze)",
    defaultDuration: "30 days",
    unitPrice: 8.50,
    stockQuantity: 85,
    minStockLevel: 15,
  },
  {
    brandName: "Cipro",
    genericName: "Ciprofloxacin",
    form: "Tablet",
    strength: "500mg",
    defaultDosage: "500mg",
    defaultFrequency: "1-0-1 (Every 12 hours)",
    defaultDuration: "7 days",
    unitPrice: 1.30,
    stockQuantity: 190,
    minStockLevel: 30,
  },
  {
    brandName: "Azithral",
    genericName: "Azithromycin",
    form: "Tablet",
    strength: "500mg",
    defaultDosage: "500mg",
    defaultFrequency: "1-0-0 (Once daily 1 hr before or 2 hr after meal)",
    defaultDuration: "3 days",
    unitPrice: 2.20,
    stockQuantity: 140,
    minStockLevel: 25,
  },
];
